import { fetchSuperAdminAuditLogs } from "@/app/super-admin/services/superAdminService";
import type { DashboardAuditLogRow } from "@/app/shared/services/dashboardSupabaseService";
import { ClipboardList } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export function AuditLogs() {
  const [logs, setLogs] = useState<DashboardAuditLogRow[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { void fetchSuperAdminAuditLogs().then(setLogs).catch((error) => toast.error(error instanceof Error ? error.message : "Unable to load audit logs.")).finally(() => setLoading(false)); }, []);
  return <div className="mx-auto max-w-[1500px] space-y-5"><header className="border-b border-[#E8DED1] pb-5"><p className="text-xs font-black uppercase tracking-[.16em] text-[#8B735B]">Super Admin</p><h1 className="mt-1 text-2xl font-black text-[#302820]">Audit Logs</h1><p className="mt-1 text-sm text-[#756A60]">Real administrative activity recorded by AptFindr.</p></header><section className="overflow-hidden rounded-xl border border-[#E8DED1] bg-white">{loading ? <div className="p-10 text-center text-sm text-[#756A60]">Loading audit logs...</div> : logs.length === 0 ? <div className="flex min-h-72 flex-col items-center justify-center p-8 text-center"><ClipboardList className="h-10 w-10 text-[#C9B8A5]" /><h2 className="mt-3 font-black text-[#302820]">No audit records yet</h2><p className="mt-1 text-sm text-[#756A60]">Important administrative actions will appear here when recorded.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-[#FAF8F5] text-xs uppercase tracking-wide text-[#756A60]"><tr><th className="p-4">Admin</th><th className="p-4">Action</th><th className="p-4">Target</th><th className="p-4">Date &amp; Time</th></tr></thead><tbody className="divide-y divide-[#EEE6DC]">{logs.map((log) => <tr key={String(log.id)} className="text-sm text-[#302820]"><td className="p-4 font-semibold">{String(log.admin_id ?? "System")}</td><td className="p-4 font-bold">{String(log.action ?? "Administrative action").replace(/_/g, " ")}</td><td className="p-4 text-[#756A60]">{String(log.target_type ?? "—")}{log.target_id ? ` · ${String(log.target_id)}` : ""}</td><td className="p-4 text-[#756A60]">{log.created_at ? new Date(log.created_at).toLocaleString("en-PH") : "—"}</td></tr>)}</tbody></table></div>}</section></div>;
}
