import { Button } from "@/app/shared/components/ui/button";
import { fetchPlatformUsers, fetchSupportRequests, updateSupportRequest, type SupportTicketRow } from "@/app/super-admin/services/superAdminService";
import type { DashboardUserRow } from "@/app/shared/services/dashboardSupabaseService";
import { LifeBuoy, Search, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";

export function HelpCenter() {
  const [tickets, setTickets] = useState<SupportTicketRow[]>([]), [users, setUsers] = useState<DashboardUserRow[]>([]);
  const [loading, setLoading] = useState(true), [search, setSearch] = useState(""), [status, setStatus] = useState("all");
  const [selected, setSelected] = useState<SupportTicketRow | null>(null), [response, setResponse] = useState("");
  const load = async () => { setLoading(true); try { const [requests, accounts] = await Promise.all([fetchSupportRequests(), fetchPlatformUsers()]); setTickets(requests); setUsers(accounts); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to load support requests."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visible = useMemo(() => tickets.filter((ticket) => { const owner = users.find((u) => u.id === ticket.user_id); const haystack = `${ticket.topic} ${ticket.message} ${owner?.name} ${owner?.email}`.toLowerCase(); return (status === "all" || ticket.status === status) && haystack.includes(search.trim().toLowerCase()); }), [tickets, users, status, search]);
  const changeStatus = async (next: string) => { if (!selected?.id) return; try { await updateSupportRequest(selected.id, next, response.trim() || undefined); toast.success(`Request marked ${next.replace("_", " ")}.`); setSelected(null); setResponse(""); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to update request."); } };
  return <div className="mx-auto max-w-[1500px] space-y-5"><header className="border-b border-[#E8DED1] pb-5"><p className="text-xs font-black uppercase tracking-[.16em] text-[#8B735B]">Super Admin</p><h1 className="mt-1 text-2xl font-black text-[#302820]">Help Center</h1><p className="mt-1 text-sm text-[#756A60]">Review and resolve support requests submitted by AptFindr users.</p></header>
    <div className="flex flex-col gap-3 rounded-xl border border-[#E8DED1] bg-white p-4 sm:flex-row"><label className="relative flex-1"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#8A8179]" /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search requests or users" className="h-11 w-full rounded-lg border border-[#E8DED1] pl-10 pr-3 text-sm outline-none focus:border-[#8B735B]" /></label><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 rounded-lg border border-[#E8DED1] bg-white px-3 text-sm"><option value="all">All statuses</option><option value="open">New</option><option value="in_progress">In Progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></div>
    <section className="overflow-hidden rounded-xl border border-[#E8DED1] bg-white">{loading ? <div className="p-10 text-center text-sm text-[#756A60]">Loading support requests...</div> : visible.length === 0 ? <div className="flex min-h-64 flex-col items-center justify-center p-8 text-center"><LifeBuoy className="h-10 w-10 text-[#C9B8A5]" /><h2 className="mt-3 font-black">No support requests</h2><p className="mt-1 text-sm text-[#756A60]">There are currently no Help Center requests matching this view.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[820px] text-left text-sm"><thead className="bg-[#FAF8F5] text-xs uppercase text-[#756A60]"><tr><th className="p-4">Request</th><th className="p-4">User</th><th className="p-4">Role</th><th className="p-4">Status</th><th className="p-4">Submitted</th><th className="p-4"></th></tr></thead><tbody className="divide-y divide-[#EEE6DC]">{visible.map((ticket) => { const owner = users.find((u) => u.id === ticket.user_id); return <tr key={ticket.id}><td className="p-4"><strong>{ticket.topic}</strong><span className="block max-w-72 truncate text-xs text-[#756A60]">{ticket.message}</span></td><td className="p-4"><strong className="block">{String(owner?.name ?? "Unknown user")}</strong><span className="text-xs text-[#756A60]">{String(owner?.email ?? ticket.contact ?? "")}</span></td><td className="p-4 capitalize">{String(owner?.role ?? "user").replace("_", " ")}</td><td className="p-4 capitalize">{String(ticket.status ?? "open").replace("_", " ")}</td><td className="p-4 text-[#756A60]">{ticket.created_at ? new Date(ticket.created_at).toLocaleString("en-PH") : "—"}</td><td className="p-4"><Button variant="outline" onClick={() => setSelected(ticket)}>View</Button></td></tr>; })}</tbody></table></div>}</section>
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><section className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-xl bg-white p-6 shadow-xl"><button onClick={() => setSelected(null)} className="float-right text-[#756A60]"><X /></button><h2 className="text-xl font-black">Support Request</h2><p className="mt-1 text-xs text-[#756A60]">Submitted {selected.created_at ? new Date(selected.created_at).toLocaleString("en-PH") : "—"}</p><dl className="mt-5 space-y-4 text-sm"><div><dt className="font-bold">Category / Subject</dt><dd className="text-[#756A60]">{selected.topic}</dd></div><div><dt className="font-bold">Description</dt><dd className="whitespace-pre-wrap text-[#756A60]">{selected.message}</dd></div><div><dt className="font-bold">Contact</dt><dd className="text-[#756A60]">{selected.contact || "Not provided"}</dd></div></dl><textarea value={response} onChange={(e) => setResponse(e.target.value)} placeholder="Optional response to the requester" className="mt-5 min-h-28 w-full rounded-lg border border-[#E8DED1] p-3 text-sm outline-none focus:border-[#8B735B]" /><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={() => void changeStatus("in_progress")}>Mark In Progress</Button><Button onClick={() => void changeStatus("resolved")} className="bg-[#8B735B] text-white">Resolve</Button><Button variant="outline" onClick={() => void changeStatus("closed")}>Close</Button></div></section></div>}
  </div>;
}
