import { Button } from "@/app/shared/components/ui/button";
import { fetchMySuperAdminProfile, saveMySuperAdminProfile, uploadSuperAdminAvatar, type SuperAdminProfile as Profile } from "@/app/super-admin/services/superAdminProfileService";
import { Camera, KeyRound, Mail, Pencil, ShieldCheck, UserRound } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { toast } from "sonner";

const formatDate = (value?: string | null) => value ? new Date(value).toLocaleString("en-PH") : "Not available";

export function SuperAdminProfile() {
  const navigate = useNavigate();
  const fileInput = useRef<HTMLInputElement>(null);
  const [profile, setProfile] = useState<Profile | null>(null), [loading, setLoading] = useState(true), [editing, setEditing] = useState(false), [saving, setSaving] = useState(false);
  const [name, setName] = useState(""), [department, setDepartment] = useState(""), [avatarUrl, setAvatarUrl] = useState(""), [avatarFile, setAvatarFile] = useState<File | null>(null);
  const load = async () => { setLoading(true); try { const value = await fetchMySuperAdminProfile(); setProfile(value); setName(value.name); setDepartment(value.department); setAvatarUrl(value.avatarUrl); setEditing(!value.hasAdminProfile); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to load profile."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const selectAvatar = (file?: File) => { if (!file) return; if (!file.type.startsWith("image/")) return void toast.error("Please select a valid image file."); if (file.size > 5 * 1024 * 1024) return void toast.error("Profile photo must be 5MB or smaller."); setAvatarFile(file); setAvatarUrl(URL.createObjectURL(file)); };
  const save = async () => { if (!profile || !name.trim()) return void toast.error("Full Name is required."); setSaving(true); try { const uploadedUrl = avatarFile ? await uploadSuperAdminAvatar(profile.id, avatarFile) : avatarUrl; await saveMySuperAdminProfile({ name, department, avatarUrl: uploadedUrl }); toast.success(profile.hasAdminProfile ? "Profile updated." : "Profile completed."); setAvatarFile(null); setEditing(false); await load(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to save profile."); } finally { setSaving(false); } };
  if (loading) return <div className="p-10 text-center text-sm text-[#756A60]">Loading Super Admin profile...</div>;
  if (!profile) return <div className="p-10 text-center text-sm text-rose-700">The Super Admin profile could not be loaded.</div>;
  const field = (label: string, value: string) => <div><dt className="text-xs font-semibold text-[#756A60]">{label}</dt><dd className="mt-1.5 text-sm font-bold text-[#302820]">{value || "Not provided"}</dd></div>;
  return <div className="mx-auto max-w-[1100px] space-y-5"><header className="flex flex-wrap items-end justify-between gap-4 border-b border-[#E8DED1] pb-5"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#8B735B]">Account</p><h1 className="mt-1 text-2xl font-black text-[#302820]">{profile.hasAdminProfile ? "Super Admin Profile" : "Complete Your Profile"}</h1><p className="mt-1 text-sm text-[#756A60]">Your identity and administrative account information.</p></div>{!editing && <Button onClick={() => setEditing(true)} className="bg-[#8B735B] text-white hover:bg-[#756A60]"><Pencil className="mr-2 h-4 w-4" />Edit Profile</Button>}</header>
    <section className="flex flex-col gap-5 rounded-xl border border-[#E8DED1] bg-white p-6 sm:flex-row sm:items-center"><div className="relative h-24 w-24 shrink-0 overflow-hidden rounded-2xl bg-[#8B735B] text-white">{avatarUrl ? <img src={avatarUrl} alt="Super Admin profile" className="h-full w-full object-cover" /> : <span className="flex h-full items-center justify-center text-3xl font-black">{name[0]?.toUpperCase() || <UserRound />}</span>}{editing && <button type="button" onClick={() => fileInput.current?.click()} className="absolute inset-x-0 bottom-0 flex h-8 items-center justify-center bg-black/55" aria-label="Choose profile photo"><Camera className="h-4 w-4" /></button>}<input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,image/gif" className="hidden" onChange={(e) => selectAvatar(e.target.files?.[0])} /></div><div className="min-w-0 flex-1">{editing ? <div className="grid gap-3"><label className="text-xs font-bold text-[#756A60]">Full Name<input value={name} onChange={(e) => setName(e.target.value)} maxLength={120} className="mt-1 h-11 w-full rounded-lg border border-[#E8DED1] px-3 text-sm text-[#302820] outline-none focus:border-[#8B735B]" /></label><label className="text-xs font-bold text-[#756A60]">Department / Position<input value={department} onChange={(e) => setDepartment(e.target.value)} maxLength={120} className="mt-1 h-11 w-full rounded-lg border border-[#E8DED1] px-3 text-sm text-[#302820] outline-none focus:border-[#8B735B]" /></label></div> : <><h2 className="truncate text-xl font-black text-[#302820]">{profile.name}</h2><p className="mt-1 truncate text-sm text-[#756A60]">{profile.email}</p></>}<span className="mt-3 inline-flex items-center gap-1 rounded-full bg-[#F3EFEA] px-3 py-1 text-xs font-black text-[#8B735B]"><ShieldCheck className="h-3.5 w-3.5" />SUPER ADMIN</span></div></section>
    {editing && <div className="flex justify-end gap-3"><Button variant="outline" disabled={saving || !profile.hasAdminProfile} onClick={() => { setEditing(false); setName(profile.name); setDepartment(profile.department); setAvatarUrl(profile.avatarUrl); setAvatarFile(null); }}>Cancel</Button><Button disabled={saving || !name.trim()} onClick={() => void save()} className="bg-[#8B735B] text-white hover:bg-[#756A60]">{saving ? "Saving..." : profile.hasAdminProfile ? "Save Changes" : "Complete Profile"}</Button></div>}
    <section className="rounded-xl border border-[#E8DED1] bg-white p-6"><h2 className="font-black text-[#302820]">Account Information</h2><dl className="mt-5 grid gap-x-10 gap-y-6 sm:grid-cols-2">{field("Full Name", profile.name)}{field("Email", profile.email)}{field("Role", "Super Admin")}{field("Admin Level", profile.adminLevel)}{field("Department / Position", profile.department)}{field("Account Status", profile.status)}{field("Date Joined", formatDate(profile.joinedAt))}{field("Last Activity", formatDate(profile.lastActivityAt))}</dl></section>
    <section className="flex flex-col gap-4 rounded-xl border border-[#E8DED1] bg-white p-6 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-black text-[#302820]">Security</h2><p className="mt-1 text-sm text-[#756A60]">Email and password changes use AptFindr’s existing secure account flows.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => navigate("/super-admin?section=admininfo")}><KeyRound className="mr-2 h-4 w-4" />Change Password</Button><Button variant="outline" onClick={() => navigate("/super-admin?section=admininfo")}><Mail className="mr-2 h-4 w-4" />Account Settings</Button></div></section>
  </div>;
}
