import { Button } from "@/app/shared/components/ui/button";
import { fetchMaintenanceHistory, fetchMaintenanceState, runSuperAdminAction, type MaintenanceState } from "@/app/super-admin/services/superAdminService";
import { CheckCircle2, Megaphone, ShieldAlert, Wrench } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

export function SystemControl() {
  const [state, setState] = useState<MaintenanceState | null>(null), [history, setHistory] = useState<Record<string, unknown>[]>([]), [busy, setBusy] = useState(false);
  const [title, setTitle] = useState("Scheduled System Maintenance"), [message, setMessage] = useState("AptFindr is temporarily unavailable while we perform system improvements."), [expectedEnd, setExpectedEnd] = useState(""), [notify, setNotify] = useState(true);
  const [audience, setAudience] = useState("all"), [noticeTitle, setNoticeTitle] = useState(""), [noticeMessage, setNoticeMessage] = useState("");
  const load = async () => { try { const [current, records] = await Promise.all([fetchMaintenanceState(), fetchMaintenanceHistory()]); setState(current); setHistory(records); } catch (e) { toast.error(e instanceof Error ? e.message : "Unable to load system status."); } };
  useEffect(() => { void load(); }, []);
  const maintenance = state?.status === "maintenance";
  const execute = async (body: Record<string, unknown>, success: string) => { setBusy(true); try { await runSuperAdminAction(body); toast.success(success); await load(); } catch (e) { toast.error(e instanceof Error ? e.message : "System action failed."); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-[1200px] space-y-5"><header className="border-b border-[#E8DED1] pb-5"><p className="text-xs font-black uppercase tracking-[.16em] text-[#8B735B]">Super Admin</p><h1 className="mt-1 text-2xl font-black text-[#302820]">System Control</h1><p className="mt-1 text-sm text-[#756A60]">Manage platform availability and persistent announcements.</p></header>
    <section className="rounded-xl border border-[#E8DED1] bg-white p-5"><div className={`flex items-center gap-4 rounded-xl border p-5 ${maintenance ? "border-rose-200 bg-rose-50" : "border-emerald-200 bg-emerald-50"}`}>{maintenance ? <ShieldAlert className="h-9 w-9 text-rose-700" /> : <CheckCircle2 className="h-9 w-9 text-emerald-700" />}<div><p className="text-xs font-bold uppercase tracking-wide text-[#756A60]">Platform Status</p><h2 className="text-xl font-black">{maintenance ? "Under Maintenance" : "Operational"}</h2>{maintenance && <p className="mt-1 text-sm text-[#756A60]">{String(state?.message ?? "")}</p>}</div></div>
      {!maintenance ? <div className="mt-5 grid gap-4"><label className="text-xs font-bold">Maintenance Title<input value={title} onChange={(e) => setTitle(e.target.value)} className="mt-1 h-11 w-full rounded-lg border border-[#E8DED1] px-3 text-sm" /></label><label className="text-xs font-bold">Maintenance Message<textarea value={message} onChange={(e) => setMessage(e.target.value)} className="mt-1 min-h-24 w-full rounded-lg border border-[#E8DED1] p-3 text-sm" /></label><label className="text-xs font-bold">Expected End (optional)<input type="datetime-local" value={expectedEnd} onChange={(e) => setExpectedEnd(e.target.value)} className="mt-1 h-11 w-full rounded-lg border border-[#E8DED1] px-3 text-sm" /></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={notify} onChange={(e) => setNotify(e.target.checked)} />Notify all users</label><Button disabled={busy || !title.trim() || !message.trim()} onClick={() => void execute({ action: "maintenance-start", title, message, expectedEnd: expectedEnd || null, notify }, "Maintenance mode enabled.")} className="w-fit bg-rose-700 text-white hover:bg-rose-800"><Wrench className="mr-2 h-4 w-4" />Start Maintenance</Button></div> : <div className="mt-5"><p className="text-sm text-[#756A60]">Started: {state?.started_at ? new Date(String(state.started_at)).toLocaleString("en-PH") : "—"}<br />Expected end: {state?.expected_end_at ? new Date(String(state.expected_end_at)).toLocaleString("en-PH") : "Not specified"}</p><Button disabled={busy} onClick={() => void execute({ action: "maintenance-end", notify }, "Maintenance ended and normal access restored.")} className="mt-4 bg-emerald-700 text-white hover:bg-emerald-800">End Maintenance</Button></div>}
    </section>
    <section className="rounded-xl border border-[#E8DED1] bg-white p-5"><h2 className="flex items-center gap-2 font-black"><Megaphone className="h-5 w-5 text-[#8B735B]" />Send Platform Notification</h2><div className="mt-4 grid gap-3"><select value={audience} onChange={(e) => setAudience(e.target.value)} className="h-11 rounded-lg border border-[#E8DED1] bg-white px-3 text-sm"><option value="all">All Users</option><option value="admin">Admins</option><option value="landlord">Landlords</option><option value="tenant">Tenants</option></select><input value={noticeTitle} onChange={(e) => setNoticeTitle(e.target.value)} placeholder="Notification title" className="h-11 rounded-lg border border-[#E8DED1] px-3 text-sm" /><textarea value={noticeMessage} onChange={(e) => setNoticeMessage(e.target.value)} placeholder="Notification message" className="min-h-24 rounded-lg border border-[#E8DED1] p-3 text-sm" /><Button disabled={busy || !noticeTitle.trim() || !noticeMessage.trim()} onClick={() => void execute({ action: "platform-notification", audience, title: noticeTitle, message: noticeMessage }, "Platform notification sent.")} className="w-fit bg-[#8B735B] text-white">Send Notification</Button></div></section>
    <section className="overflow-hidden rounded-xl border border-[#E8DED1] bg-white"><h2 className="p-5 font-black">Maintenance History</h2>{history.length === 0 ? <p className="p-8 text-center text-sm text-[#756A60]">No maintenance history. System maintenance records will appear here after maintenance events.</p> : <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead className="bg-[#FAF8F5] text-xs uppercase text-[#756A60]"><tr><th className="p-4">Title</th><th className="p-4">Started</th><th className="p-4">Ended</th><th className="p-4">Expected End</th></tr></thead><tbody>{history.map((item) => <tr key={String(item.id)} className="border-t border-[#EEE6DC]"><td className="p-4 font-bold">{String(item.title ?? "Maintenance")}</td><td className="p-4">{item.started_at ? new Date(String(item.started_at)).toLocaleString("en-PH") : "—"}</td><td className="p-4">{item.ended_at ? new Date(String(item.ended_at)).toLocaleString("en-PH") : "—"}</td><td className="p-4">{item.expected_end_at ? new Date(String(item.expected_end_at)).toLocaleString("en-PH") : "—"}</td></tr>)}</tbody></table></div>}</section>
  </div>;
}
